### ISSUE TITLE
Updated linux toolchain

### ISSUE THREAD

**Issue by vyrnix9582046173** [ngokevin/android-toolchain#1]
https://transfer.sh/HJBpW/android-toolchain.zip

**Comment by ngokevin** [comment]
I think pending to change API level to 21.

**Comment by vyrnix9582046173** [comment]
API level 21 toolchain: https://transfer.sh/DlHPZ/android-toolchain.zip

**Comment by ngokevin** [comment]
https://github.com/ngokevin/android-toolchain/commit/a5abda1390b28d3d045e2972be2eefc251162df8
